### ISSUE TITLE
What' the difference between libseq and mapidx?

### ISSUE THREAD

**Issue by USTClj** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#14]
Hi! Thank you for your awesome simplified work!
Could you please help me explain the use and function between libseq and mapidx?
Looking forward to you replying!

**Comment by last-one** [comment]
I rewrite the script based on the `[origin code](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/python/demo.ipynb)`

**Comment by USTClj** [comment]
Thank you！
