### ISSUE TITLE
unexpected key "0.weight" in state_dict

### ISSUE THREAD

**Issue by CrossLee1** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#15]
I downloaded the pytorch model as stated in caffe2pytorch/README.md, 
but when I load the model in 
        `model.load_state_dict(state_dict)`, 
an error occurs: 
        `KeyError: 'unexpected key "0.weight" in 'state_dict'`

Hope to get your response, thanks~

**Comment by last-one** [comment]
change 'name = k[7:]' to 'name = k'.
