### ISSUE TITLE
Pytorch error when testing with pretrained model

### ISSUE THREAD

**Issue by nikjetchev** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#16]
Dear project creators

I followed your instructions and downloaded from the GoogleDrive link the pretrained torch model "coco_pose_iter_440000.pth.tar".
However, I get an error as copied below, some values are incompatible.

Can you please help me solve that issue, I guess there might be 3 reasons for that problem:

1) the model file in the google drive is obsolete

2) I have installed another version of Pytorch than required

3) some issue in your code

Any help is appreciated
thanks
Nikolay

python test_pose.py --image ski.jpg
Traceback (most recent call last):
  File "test_pose.py", line 314, in <module>
    model = construct_model(args)
  File "test_pose.py", line 42, in construct_model
    model.load_state_dict(state_dict)
  File "/home/njetchev/anaconda2/envs/p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "0.weight" in state_dict'

**Comment by last-one** [comment]
please see this [issue](https://github.com/last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation/issues/15)
