### ISSUE TITLE
Unable to resolve host address when downloading the model

### ISSUE THREAD

**Issue by KaiWU17TUM** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#19]
Hi,
I got this following error when downloading the caffe model:
wget: unable to resolve host address "posefs1.perception.cs.cmn.edu.users"

how can I solve this error or where else can I get this model?

thanks in advance.

**Comment by KaiWU17TUM** [comment]
And another problem is: when I try to unarchive the pytorch model "coco_pose_iter_440000.pth.tar" by executing:
bash-3.2$ tar -xvf coco_pose_iter_440000.pth.tar

Error:
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

I've googled a lot but still can't solve it.

**Comment by last-one** [comment]
If I remember correctly, the google driver or baidu don't support the use of wget to download model.

**Comment by qy-feng** [comment]
The url was probably changed. I've used the link below this week and it works. 
  http://posefs1.perception.cs.cmu.edu/Users/tsimon/Projects/coco/data/models/coco/pose_iter_440000.caffemodel

**Comment by KaiWU17TUM** [comment]
thanks for the quick response. I've got the pytorch model now.
But when running the test_pose.py, I got the following error. Does this happen when you load the model??

File "test_pose.py", line 314, in <module>
    model = construct_model(args)
File "test_pose.py", line 34, in construct_model
    state_dict = torch.load(args.model)['state_dict']
File "/usr/prakt/w259/Documents/dl4cv/.dl4cv/lib/python3.5/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
File "/usr/prakt/w259/Documents/dl4cv/.dl4cv/lib/python3.5/site-packages/torch/serialization.py", line 416, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.

**Comment by KaiWU17TUM** [comment]
fixed now!
thx!
