### ISSUE TITLE
Newly implemented openpose (pytorch)

### ISSUE THREAD

**Issue by youansheng** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#25]
https://github.com/youansheng/pytorch-cv/tree/master/methods/pose

**Comment by liuxiuxuhaodong** [comment]
hi ,do you deleted your file?I want to research your demo.

**Comment by youdonny** [comment]
@liuxiuxuhaodong  New Site: https://github.com/CVBox/PyTorchCV
