### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by marc-tonsen** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#28]
Hi,

would you mind adding a license to the repo like e.g. the [MIT license](https://en.wikipedia.org/wiki/MIT_License)? We are interested in using part of the code in our open-source [project](https://github.com/pupil-labs/pupil).

Thanks!
Marc

**Comment by last-one** [comment]
Done~

**Comment by marc-tonsen** [comment]
Thank you very much!
