### ISSUE TITLE
Download the data set, annotations and COCO official toolbox

### ISSUE THREAD

**Issue by wangfei-cs** [last-one/Pytorch_Realtime_Multi-Person_Pose_Estimation#9]
I'm confused about downloading what dataset and what annotations. Could you help me?

**Comment by last-one** [comment]
I used COCO2017 to train and test. COCO2014 and COCO2017 have the same images and their split methods are different.

**Comment by last-one** [comment]
I used COCO2017 to train and test. COCO2014 and COCO2017 have the same images and their split methods are different.

**Comment by wangfei-cs** [comment]
Thank you for quick response!
Which ones should I download?

Images: 
2017 Train images [118K/18GB]
2017 Val images [5K/1GB]
2017 Test images [41K/6GB]
2017 Unlabeled images [123K/19GB]

Annotation:
2017 Train/Val annotations [241MB]
2017 Stuff Train/Val annotations [401MB]
2017 Testing Image info [1MB]
2017 Unlabeled Image info [4MB]


And, when I run python generate_json_mask.py 
filelist_fp = open(args.filelist_path, 'w')
TypeError: expected str, bytes or os.PathLike object, not NoneType

It must I don't set ann_path, json_path, mask_dir, filelist_path, masklist_path
Should I set them after I download the coco dataset?
